name: Build Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: Xuanwo
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        repository: xuanwo/dont-starve-together
        tags: latest
